routes:

    homepage:
        path: /
        controller: R2AppBundle:FrontPage:index

    login:
        path: /login
        controller: R2AppBundle:User:login
        methods: [GET]

    login_check:
        path: /login
        controller: R2AppBundle:User:loginCheck
        methods: [POST]

    logout:
        path: /logout/{token}
        controller: R2AppBundle:User:logout
        requirements: { token: "(.*)+" }
